[build-system]
requires = ["setuptools>=65.0", "wheel", "pybind11>=2.10", "cython>=0.30", "numpy"]
build-backend = "setuptools.build_meta"

[project]
name = "pam_scripts"
version = "0.0.0"
authors = [
  { name="Christian Moulsdale", email="cm43@sanger.ac.uk" },
]
description = "A collection of scripts to help with PAM analysis"
readme = "README.md"
requires-python = ">=3.5"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dynamic = ["dependencies"]

[project.scripts]
kpy = "pam_scripts.kpy:main"
kpy-count = "pam_scripts.kmc:main"
kpy-sketch = "pam_scripts.sketch:main"
kpy-triangle = "pam_scripts.triangle:main"
kpy-embed = "pam_scripts.embed:main"
kpy-embed2 = "pam_scripts.embed2:main"
kpy-plot = "pam_scripts.plot:main"
kpy-compare = "pam_scripts.compare:main"
filter-sig = "pam_scripts.filter_sig:main"
sourmash2phylip = "pam_scripts.sourmash2phylip:main"
sourmash2clusters = "pam_scripts.sourmash2clusters:main"
cluster2sketch = "pam_scripts.cluster2sketch:main"
mergeClusters = "pam_scripts.mergeClusters:main"
concat_acgt = "pam_scripts.concat_acgt:main"
process_reads = "pam_scripts.process_reads:main"

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }
